### ISSUE TITLE
New Screen Splash for App

### ISSUE THREAD

**Issue by jaisadana1999** [scriptfoundation/AppScriptFoundation#2]
Make a New Screen Splash for the flutter app based on new foundation logo

Below attached the new logo
![46463_Script Foundation_Logo_RD_01.png](https://user-images.githubusercontent.com/62330419/106152263-3f083c80-61a3-11eb-8ca5-d1def3d7cbd7.png)

**Comment by Vrushti24** [comment]
I want to work on this issue

**Comment by jaisadana1999** [comment]
Go ahead @Vrushti24

**Comment by Vrushti24** [comment]
Is these counted under SWOC just asking?

**Comment by Vrushti24** [comment]
The app is not running in my device what should i do ?

**Comment by jaisadana1999** [comment]
> Is these counted under SWOC just asking?

Yes

**Comment by jaisadana1999** [comment]
> The app is not running in my device what should i do ?

You can download the from play store or run the flutter app by seeing the read me

```

**Comment by Vrushti24** [comment]
Ok, I'll check it out.

**Comment by Vrushti24** [comment]
PR #11 please check that

**Comment by jaisadana1999** [comment]
Please provide the screenshot of the Splash Screen
@Vrushti24

**Comment by Vrushti24** [comment]
Ohh..okay

**Comment by Vrushti24** [comment]
I will send u tomorrow is it okay ?

**Comment by jaisadana1999** [comment]
Sure @Vrushti24
