### ISSUE TITLE
Message Bot to contact Support Team

### ISSUE THREAD

**Issue by jaisadana1999** [scriptfoundation/AppScriptFoundation#8]
Will be using Twak.to api for making the bot

**Comment by Imadarshsri** [comment]
Hey, I looked into `twak.to` API, only JS API is available there. How can I implement it in flutter

**Comment by jaisadana1999** [comment]
@Imadarshsri 
Check this out
https://pub.dev/documentation/flutter_tawk/latest/

**Comment by Imadarshsri** [comment]
@jaisadana1999...Thanks,  I will see it..start working on this

**Comment by jaisadana1999** [comment]
Great go ahead @Imadarshsri
